package org.dsgroup.journeycraft.diary.service.impl;

import lombok.RequiredArgsConstructor;
import org.dsgroup.journeycraft.common.enums.ResponseCodeEnum;
import org.dsgroup.journeycraft.common.exception.BusinessException;
import org.dsgroup.journeycraft.diary.dto.DiaryCreateDTO;
import org.dsgroup.journeycraft.diary.entity.Comment;
import org.dsgroup.journeycraft.diary.entity.Diary;
import org.dsgroup.journeycraft.diary.repository.CommentRepository;
import org.dsgroup.journeycraft.diary.repository.DiaryRepository;
import org.dsgroup.journeycraft.diary.service.DiaryService;
import org.dsgroup.journeycraft.diary.vo.reqvo.CommentCreateReqVO;
import org.dsgroup.journeycraft.diary.vo.rspvo.CommentRspVO;
import org.dsgroup.journeycraft.diary.vo.rspvo.DiaryDetailRspVO;
import org.dsgroup.journeycraft.diary.vo.rspvo.DiaryLikeRspVO;
import org.dsgroup.journeycraft.diary.vo.rspvo.DiaryListRspVO;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import java.util.stream.Collectors;

/**
 * 日记服务实现
 */
@Service
@RequiredArgsConstructor
public class DiaryServiceImpl implements DiaryService {

    private final DiaryRepository diaryRepository;
    private final CommentRepository commentRepository;

    /**
     * 内存存储用户点赞记录 (Key: diaryId:userId, Value: liked)
     * 注意：生产环境应该使用数据库表存储
     */
    private final Set<String> likedRecords = ConcurrentHashMap.newKeySet();

    /**
     * 创建日记
     *
     * @param dto 创建日记数据传输对象
     * @param currentUserId 当前登录用户 ID
     * @return 日记 ID
     */
    @Override
    public String createDiary(DiaryCreateDTO dto, Long currentUserId) {
        // 构建 Diary 实体
        Diary diary = Diary.builder()
                .userId(currentUserId)
                .title(dto.getTitle())
                .content(dto.getContent())
                .scenicAreaId(dto.getScenicAreaId())
                .tripId(dto.getTripId())
                .coverImage(dto.getCoverImage())
                .images(dto.getImages())
                .videos(dto.getVideos())
                .path(convertToPathNodes(dto.getPath()))
                .tags(dto.getTags())
                .rating(dto.getRating())
                .mood(dto.getMood())
                .weather(dto.getWeather())
                .companions(dto.getCompanions())
                .status(dto.getStatus() != null ? dto.getStatus() : 1)
                .isAutoGenerated(false)
                .likeCount(0L)
                .viewCount(0L)
                .commentCount(0L)
                .shareCount(0L)
                .favoriteCount(0L)
                .createdAt(LocalDateTime.now())
                .updatedAt(LocalDateTime.now())
                .build();

        // 自动生成摘要（如果未提供）
        if (diary.getSummary() == null || diary.getSummary().isEmpty()) {
            diary.setSummary(generateSummary(dto.getContent()));
        }

        // 保存到 MongoDB
        Diary savedDiary = diaryRepository.save(diary);

        return savedDiary.getId();
    }

    /**
     * 查询日记列表
     */
    @Override
    public List<DiaryListRspVO> getDiaryList(Long userId, String tags, String sortBy, Integer page, Integer size) {
        // 默认参数
        if (page == null || page < 1) page = 1;
        if (size == null || size < 1) size = 10;
        if (size > 100) size = 100;

        // 构建排序
        Sort sort = buildSort(sortBy);

        // 查询数据（只查询公开的日记）
        List<Diary> diaries;
        if (userId != null) {
            diaries = diaryRepository.findByUserIdAndStatus(userId, 1, PageRequest.of(page - 1, size, sort));
        } else {
            diaries = diaryRepository.findByStatus(1, PageRequest.of(page - 1, size, sort));
        }

        // 标签过滤（内存过滤）
        if (tags != null && !tags.isEmpty()) {
            String[] tagArray = tags.split(",");
            diaries = diaries.stream()
                    .filter(d -> d.getTags() != null &&
                            d.getTags().stream().anyMatch(t -> {
                                for (String tag : tagArray) {
                                    if (t.contains(tag.trim())) return true;
                                }
                                return false;
                            }))
                    .collect(Collectors.toList());
        }

        // 转换为 VO
        return diaries.stream()
                .map(this::convertToListVO)
                .collect(Collectors.toList());
    }

    /**
     * 查询日记详情
     */
    @Override
    public DiaryDetailRspVO getDiaryDetail(String id) {
        Diary diary = diaryRepository.findById(id)
                .orElseThrow(() -> new BusinessException(ResponseCodeEnum.DIARY_NOT_FOUND,"日记不存在"));

        // 检查是否公开（私密日记只有自己能看到，这里简化处理）
        if (diary.getStatus() == 0) {
            throw new RuntimeException("该日记为私密日记");
        }

        return convertToDetailVO(diary);
    }

    /**
     * 构建排序条件
     */
    private Sort buildSort(String sortBy) {
        if ("heat".equals(sortBy)) {
            // 热度 = 点赞 + 浏览 + 评论
            return Sort.by(Sort.Direction.DESC, "likeCount", "viewCount", "commentCount");
        } else if ("rating".equals(sortBy)) {
            return Sort.by(Sort.Direction.DESC, "rating");
        } else {
            // 默认按时间倒序
            return Sort.by(Sort.Direction.DESC, "createdAt");
        }
    }

    /**
     * 将 Diary 实体转换为列表 VO
     */
    private DiaryListRspVO convertToListVO(Diary diary) {
        return DiaryListRspVO.builder()
                .id(diary.getId())
                .userId(diary.getUserId())
                .userNickname("用户" + diary.getUserId()) // TODO: 从 user 模块获取
                .userAvatar("http://localhost:9000/journeycraft/avatar/default.jpg") // TODO: 从 user 模块获取
                .title(diary.getTitle())
                .summary(diary.getSummary())
                .coverImage(diary.getCoverImage())
                .tags(diary.getTags())
                .rating(diary.getRating())
                .likeCount(diary.getLikeCount())
                .images(diary.getImages())
                .videos(diary.getVideos())
                .viewCount(diary.getViewCount())
                .commentCount(diary.getCommentCount())
                .createdAt(diary.getCreatedAt())
                .build();
    }

    /**
     * 将 Diary 实体转换为详情 VO
     */
    private DiaryDetailRspVO convertToDetailVO(Diary diary) {
        return DiaryDetailRspVO.builder()
                .id(diary.getId())
                .userId(diary.getUserId())
                .userNickname("用户" + diary.getUserId()) // TODO: 从 user 模块获取
                .userAvatar("http://localhost:9000/journeycraft/avatar/default.jpg") // TODO: 从 user 模块获取
                .title(diary.getTitle())
                .content(diary.getContent())
                .scenicAreaId(diary.getScenicAreaId())
                .tripId(diary.getTripId())
                .coverImage(diary.getCoverImage())
                .images(diary.getImages())
                .videos(diary.getVideos())
                .path(convertToPathNodeVOs(diary.getPath()))
                .tags(diary.getTags())
                .rating(diary.getRating())
                .mood(diary.getMood())
                .weather(diary.getWeather())
                .companions(diary.getCompanions())
                .isAutoGenerated(diary.getIsAutoGenerated())
                .aiSummary(diary.getAiSummary())
                .likeCount(diary.getLikeCount())
                .viewCount(diary.getViewCount())
                .commentCount(diary.getCommentCount())
                .isLiked(false) // TODO: 根据当前用户判断
                .status(diary.getStatus())
                .createdAt(diary.getCreatedAt())
                .updatedAt(diary.getUpdatedAt())
                .build();
    }

    /**
     * 将路径节点转换为 VO
     */
    private List<DiaryDetailRspVO.PathNodeVO> convertToPathNodeVOs(List<Diary.PathNode> pathNodes) {
        if (pathNodes == null) return new ArrayList<>();
        return pathNodes.stream()
                .map(node -> DiaryDetailRspVO.PathNodeVO.builder()
                        .nodeName(node.getNodeName())
                        .nodeId(node.getNodeId())
                        .timestamp(node.getTimestamp())
                        .lat(node.getLocation() != null ? node.getLocation().getLat() : null)
                        .lng(node.getLocation() != null ? node.getLocation().getLng() : null)
                        .photoCount(node.getPhotoCount())
                        .images(node.getImages())
                        .videos(node.getVideos())
                        .build())
                .collect(Collectors.toList());
    }

    /**
     * 将 DTO 的路径节点转换为实体的路径节点
     */
    private List<Diary.PathNode> convertToPathNodes(List<DiaryCreateDTO.PathNodeDTO> pathNodeDTOs) {
        if (pathNodeDTOs == null || pathNodeDTOs.isEmpty()) {
            return null;
        }

        return pathNodeDTOs.stream()
                .map(dto -> Diary.PathNode.builder()
                        .nodeName(dto.getNodeName())
                        .nodeId(dto.getNodeId())
                        .timestamp(dto.getTimestamp() != null ?
                                LocalDateTime.parse(dto.getTimestamp()) : null)
                        .location(dto.getLat() != null && dto.getLng() != null ?
                                Diary.Location.builder()
                                        .lat(dto.getLat())
                                        .lng(dto.getLng())
                                        .build() : null)
                        .photoCount(dto.getPhotoCount())
                        .images(dto.getImages())
                        .videos(dto.getVideos())
                        .build())
                .collect(Collectors.toList());
    }

    /**
     * 自动生成摘要
     * 截取内容的前 100 个字符（去除 Markdown 标记）
     */
    private String generateSummary(String content) {
        if (content == null || content.isEmpty()) {
            return "";
        }

        // 去除 Markdown 标记（简单的#、*等）
        String plainText = content.replaceAll("#+", "")
                                  .replaceAll("\\*+", "")
                                  .replaceAll("\\n+", " ")
                                  .trim();

        // 截取前 100 个字符
        if (plainText.length() > 100) {
            return plainText.substring(0, 100) + "...";
        }

        return plainText;
    }

    /**
     * 更新日记
     */
    @Override
    public void updateDiary(String id, DiaryCreateDTO dto, Long currentUserId) {
        Diary diary = diaryRepository.findById(id)
                .orElseThrow(() -> new BusinessException(ResponseCodeEnum.DIARY_NOT_FOUND,"日记不存在"));

        // 所有权校验
        if (diary.getUserId() == null || !diary.getUserId().equals(currentUserId)) {
            throw new BusinessException(ResponseCodeEnum.PERMISSION_DENIED, "无权修改该日记");
        }

        // 更新字段
        diary.setTitle(dto.getTitle());
        diary.setContent(dto.getContent());
        diary.setScenicAreaId(dto.getScenicAreaId());
        diary.setTripId(dto.getTripId());
        diary.setCoverImage(dto.getCoverImage());
        diary.setImages(dto.getImages());
        diary.setVideos(dto.getVideos());
        diary.setPath(convertToPathNodes(dto.getPath()));
        diary.setTags(dto.getTags());
        diary.setRating(dto.getRating());
        diary.setMood(dto.getMood());
        diary.setWeather(dto.getWeather());
        diary.setCompanions(dto.getCompanions());
        diary.setStatus(dto.getStatus() != null ? dto.getStatus() : 1);
        diary.setUpdatedAt(LocalDateTime.now());

        // 自动生成摘要（如果未提供）
        if (diary.getSummary() == null || diary.getSummary().isEmpty()) {
            diary.setSummary(generateSummary(dto.getContent()));
        }

        diaryRepository.save(diary);
    }

    /**
     * 删除日记
     */
    @Override
    public void deleteDiary(String id, Long currentUserId) {
        Diary diary = diaryRepository.findById(id)
                .orElseThrow(() -> new BusinessException(ResponseCodeEnum.DIARY_NOT_FOUND,"日记不存在"));

        // 所有权校验
        if (diary.getUserId() == null || !diary.getUserId().equals(currentUserId)) {
            throw new BusinessException(ResponseCodeEnum.PERMISSION_DENIED, "无权删除该日记");
        }

        diaryRepository.deleteById(id);

        // 删除相关评论
        commentRepository.deleteByDiaryId(id);
    }

    /**
     * 点赞日记 (切换模式)
     */
    @Override
    public DiaryLikeRspVO toggleLike(String id, Long currentUserId) {
        Diary diary = diaryRepository.findById(id)
                .orElseThrow(() -> new BusinessException(ResponseCodeEnum.DIARY_NOT_FOUND,"日记不存在"));

        String recordKey = id + ":" + currentUserId;
        boolean isLiked = likedRecords.contains(recordKey);

        if (isLiked) {
            // 取消点赞
            likedRecords.remove(recordKey);
            diary.setLikeCount(Math.max(0, diary.getLikeCount() - 1));
        } else {
            // 点赞
            likedRecords.add(recordKey);
            diary.setLikeCount(diary.getLikeCount() + 1);
        }

        diaryRepository.save(diary);

        return DiaryLikeRspVO.builder()
                .likeCount(diary.getLikeCount())
                .isLiked(!isLiked)
                .build();
    }

    /**
     * 添加评论
     */
    @Override
    public String addComment(String diaryId, CommentCreateReqVO reqVO, Long currentUserId) {
        // 验证日记是否存在
        if (!diaryRepository.existsById(diaryId)) {
            throw new BusinessException(ResponseCodeEnum.DIARY_NOT_FOUND,"日记不存在");
        }

        Comment comment = Comment.builder()
                .diaryId(diaryId)
                .userId(currentUserId)
                .userNickname("用户" + currentUserId) // TODO: 从 user 模块获取
                .userAvatar("http://localhost:9000/journeycraft/avatar/default.jpg")
                .parentId(reqVO.getParentId())
                .content(reqVO.getContent())
                .images(reqVO.getImages())
                .likeCount(0L)
                .replyCount(0L)
                .status(1)
                .createdAt(LocalDateTime.now())
                .build();

        Comment savedComment = commentRepository.save(comment);

        // 如果是回复评论，增加父评论的回复数
        if (reqVO.getParentId() != null) {
            Comment parentComment = commentRepository.findById(reqVO.getParentId())
                    .orElseThrow(() -> new BusinessException(ResponseCodeEnum.DATA_NOT_EXIST, "父评论不存在"));
            parentComment.setReplyCount(parentComment.getReplyCount() + 1);
            commentRepository.save(parentComment);
        } else {
            // 增加日记的评论数
            Diary diary = diaryRepository.findById(diaryId)
                    .orElseThrow(() -> new BusinessException(ResponseCodeEnum.DIARY_NOT_FOUND, "日记不存在"));
            diary.setCommentCount(diary.getCommentCount() + 1);
            diaryRepository.save(diary);
        }

        return savedComment.getId();
    }

    /**
     * 查询评论列表
     */
    @Override
    public List<CommentRspVO> getCommentList(String diaryId, Integer page, Integer size) {
        // 默认参数
        if (page == null || page < 1) page = 1;
        if (size == null || size < 1) size = 10;
        if (size > 100) size = 100;

        // 查询评论（只查询显示的评论，先查父评论）
        List<Comment> comments = commentRepository.findByDiaryIdAndStatus(diaryId, 1,
                PageRequest.of(page - 1, size, Sort.by(Sort.Direction.DESC, "createdAt")));

        return comments.stream()
                .map(this::convertToCommentVO)
                .collect(Collectors.toList());
    }

    /**
     * 将 Comment 实体转换为 VO
     */
    private CommentRspVO convertToCommentVO(Comment comment) {
        List<CommentRspVO> replies = new ArrayList<>();
        // 如果是父评论，查询回复
        if (comment.getParentId() == null) {
            List<Comment> replyComments = commentRepository.findByParentId(comment.getId());
            replies = replyComments.stream()
                    .map(this::convertToCommentVO)
                    .collect(Collectors.toList());
        }

        return CommentRspVO.builder()
                .id(comment.getId())
                .userId(comment.getUserId())
                .userNickname(comment.getUserNickname())
                .userAvatar(comment.getUserAvatar())
                .content(comment.getContent())
                .images(comment.getImages())
                .likeCount(comment.getLikeCount())
                .replyCount(comment.getReplyCount())
                .createdAt(comment.getCreatedAt())
                .replies(replies)
                .build();
    }

    /**
     * 删除评论
     */
    @Override
    public void deleteComment(String commentId, Long currentUserId) {
        // 1. 查询评论是否存在
        Comment comment = commentRepository.findById(commentId)
                .orElseThrow(() -> new BusinessException(ResponseCodeEnum.DATA_NOT_EXIST, "评论不存在"));

        // 2. 查询日记是否存在
        Diary diary = diaryRepository.findById(comment.getDiaryId())
                .orElseThrow(() -> new BusinessException(ResponseCodeEnum.DIARY_NOT_FOUND, "日记不存在"));

        // 3. 权限校验 (注意：userId 可能为 null)
        boolean isCommentOwner = comment.getUserId() != null && comment.getUserId().equals(currentUserId);
        boolean isDiaryOwner = diary.getUserId() != null && diary.getUserId().equals(currentUserId);

        if (!isCommentOwner && !isDiaryOwner) {
            throw new BusinessException(ResponseCodeEnum.PERMISSION_DENIED, "无权删除该评论");
        }

        // 4. 软删除评论 (修改 status=0)
        comment.setStatus(0);
        commentRepository.save(comment);

        // 5. 更新计数
        if (comment.getParentId() == null) {
            // 父评论：减少日记评论数
            diary.setCommentCount(Math.max(0, diary.getCommentCount() - 1));
            diaryRepository.save(diary);
        } else {
            // 回复评论：减少父评论回复数
            Comment parentComment = commentRepository.findById(comment.getParentId()).orElse(null);
            if (parentComment != null && parentComment.getStatus() == 1) {
                parentComment.setReplyCount(Math.max(0, parentComment.getReplyCount() - 1));
                commentRepository.save(parentComment);
            }
        }
    }
}
