package org.dsgroup.journeycraft.diary.service.impl;

import lombok.RequiredArgsConstructor;
import org.dsgroup.journeycraft.diary.dto.DiaryCreateDTO;
import org.dsgroup.journeycraft.diary.entity.Diary;
import org.dsgroup.journeycraft.diary.repository.DiaryRepository;
import org.dsgroup.journeycraft.diary.service.DiaryService;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.stream.Collectors;

/**
 * 日记服务实现
 */
@Service
@RequiredArgsConstructor
public class DiaryServiceImpl implements DiaryService {

    private final DiaryRepository diaryRepository;

    /**
     * 创建日记
     * @param dto 创建日记数据传输对象
     * @return 日记 ID
     */
    @Override
    public String createDiary(DiaryCreateDTO dto) {
        // 构建 Diary 实体
        Diary diary = Diary.builder()
                .title(dto.getTitle())
                .content(dto.getContent())
                .scenicAreaId(dto.getScenicAreaId())
                .tripId(dto.getTripId())
                .coverImage(dto.getCoverImage())
                .images(dto.getImages())
                .videos(dto.getVideos())
                .path(convertToPathNodes(dto.getPath()))
                .tags(dto.getTags())
                .rating(dto.getRating())
                .mood(dto.getMood())
                .weather(dto.getWeather())
                .companions(dto.getCompanions())
                .status(dto.getStatus() != null ? dto.getStatus() : 1)
                .isAutoGenerated(false)
                .likeCount(0L)
                .viewCount(0L)
                .commentCount(0L)
                .shareCount(0L)
                .favoriteCount(0L)
                .createdAt(LocalDateTime.now())
                .updatedAt(LocalDateTime.now())
                .build();

        // 自动生成摘要（如果未提供）
        if (diary.getSummary() == null || diary.getSummary().isEmpty()) {
            diary.setSummary(generateSummary(dto.getContent()));
        }

        // 保存到 MongoDB
        Diary savedDiary = diaryRepository.save(diary);

        return savedDiary.getId();
    }

    /**
     * 将 DTO 的路径节点转换为实体的路径节点
     */
    private java.util.List<Diary.PathNode> convertToPathNodes(java.util.List<DiaryCreateDTO.PathNodeDTO> pathNodeDTOs) {
        if (pathNodeDTOs == null || pathNodeDTOs.isEmpty()) {
            return null;
        }

        return pathNodeDTOs.stream()
                .map(dto -> Diary.PathNode.builder()
                        .nodeName(dto.getNodeName())
                        .nodeId(dto.getNodeId())
                        .timestamp(dto.getTimestamp() != null ?
                                java.time.LocalDateTime.parse(dto.getTimestamp()) : null)
                        .location(dto.getLat() != null && dto.getLng() != null ?
                                Diary.Location.builder()
                                        .lat(dto.getLat())
                                        .lng(dto.getLng())
                                        .build() : null)
                        .photoCount(dto.getPhotoCount())
                        .images(dto.getImages())
                        .videos(dto.getVideos())
                        .build())
                .collect(Collectors.toList());
    }

    /**
     * 自动生成摘要
     * 截取内容的前 100 个字符（去除 Markdown 标记）
     */
    private String generateSummary(String content) {
        if (content == null || content.isEmpty()) {
            return "";
        }

        // 去除 Markdown 标记（简单的#、*等）
        String plainText = content.replaceAll("#+", "")
                                  .replaceAll("\\*+", "")
                                  .replaceAll("\\n+", " ")
                                  .trim();

        // 截取前 100 个字符
        if (plainText.length() > 100) {
            return plainText.substring(0, 100) + "...";
        }

        return plainText;
    }
}
