package org.dsgroup.journeycraft.diary.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

import java.time.LocalDateTime;
import java.util.List;

/**
 * 日记文档实体
 * 对应 MongoDB 中的 diary 集合
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "diary")
public class Diary {

    /**
     * 日记 ID (MongoDB ObjectId)
     */
    @Id
    private String id;

    /**
     * 作者 ID
     */
    @Indexed
    private Long userId;

    /**
     * 关联小组 ID (可选)
     */
    private Long groupId;

    /**
     * 关联景区 ID 列表
     */
    private List<Long> scenicAreaId;

    /**
     * 关联行程 ID
     */
    private Long tripId;

    /**
     * 标题
     */
    private String title;

    /**
     * 内容 (Markdown 格式)
     */
    private String content;

    /**
     * 摘要 (自动生成)
     */
    private String summary;

    /**
     * 封面图 URL
     */
    private String coverImage;

    /**
     * 图片 URL 列表
     */
    private List<String> images;

    /**
     * 视频 URL 列表
     */
    private List<String> videos;

    /**
     * 游览路径
     */
    private List<PathNode> path;

    /**
     * 标签
     */
    private List<String> tags;

    /**
     * 评分 0-5
     */
    private Double rating;

    /**
     * 心情：happy/neutral/sad/excited/tired
     */
    private String mood;

    /**
     * 天气
     */
    private String weather;

    /**
     * 同行人
     */
    private List<String> companions;

    /**
     * 是否 AI 生成
     */
    @Field("isAutoGenerated")
    private Boolean isAutoGenerated;

    /**
     * AI 摘要
     */
    private String aiSummary;

    /**
     * 点赞数
     */
    @Builder.Default
    private Long likeCount = 0L;

    /**
     * 浏览数
     */
    @Builder.Default
    private Long viewCount = 0L;

    /**
     * 评论数
     */
    @Builder.Default
    private Long commentCount = 0L;

    /**
     * 分享数
     */
    @Builder.Default
    private Long shareCount = 0L;

    /**
     * 收藏数
     */
    @Builder.Default
    private Long favoriteCount = 0L;

    /**
     * 状态：0-私密 1-公开
     */
    @Builder.Default
    private Integer status = 1;

    /**
     * 创建时间
     */
    private LocalDateTime createdAt;

    /**
     * 更新时间
     */
    private LocalDateTime updatedAt;

    /**
     * 游览路径节点
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class PathNode {

        /**
         * 节点名称
         */
        private String nodeName;

        /**
         * 节点 ID
         */
        private Long nodeId;

        /**
         * 时间戳
         */
        private LocalDateTime timestamp;

        /**
         * 位置坐标
         */
        private Location location;

        /**
         * 照片数量
         */
        private Integer photoCount;

        /**
         * 节点图片列表
         */
        private List<String> images;

        /**
         * 节点视频列表
         */
        private List<String> videos;
    }

    /**
     * 位置坐标
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class Location {

        /**
         * 纬度
         */
        private Double lat;

        /**
         * 经度
         */
        private Double lng;
    }
}
