import { request } from './http'
import { mockService } from '@/mock/service'
import { invoke } from './common'
import type { Diary } from '@/types/domain'

export function listDiaries() {
  return invoke(
    async () => (await mockService.diary.list()).data as Diary[],
    () => request<Diary[]>({ url: '/diary/list', method: 'GET' }),
  )
}

export function getDiary(id: number) {
  return invoke(
    async () => (await mockService.diary.detail(id)).data as Diary,
    () => request<Diary>({ url: `/diary/${id}`, method: 'GET' }),
  )
}

export function createDiary(payload: Partial<Diary>) {
  return invoke(
    async () => (await mockService.diary.create(payload)).data as Diary,
    () => request<Diary>({ url: '/diary', method: 'POST', data: payload }),
  )
}

export function updateDiary(id: number, payload: Partial<Diary>) {
  return invoke(
    async () => (await mockService.diary.update(id, payload)).data as Diary,
    () => request<Diary>({ url: `/diary/${id}`, method: 'PUT', data: payload }),
  )
}

export function deleteDiary(id: number) {
  return invoke(
    async () => (await mockService.diary.delete(id)).data as Record<string, unknown>,
    () => request<Record<string, unknown>>({ url: `/diary/${id}`, method: 'DELETE' }),
  )
}

export function likeDiary(id: number) {
  return invoke(
    async () => (await mockService.diary.like(id)).data as Record<string, unknown>,
    () => request<Record<string, unknown>>({ url: `/diary/${id}/like`, method: 'POST' }),
  )
}

export function commentDiary(id: number, content: string) {
  return invoke(
    async () => (await mockService.diary.comment(id, content)).data as Record<string, unknown>,
    () => request<Record<string, unknown>>({ url: `/diary/${id}/comment`, method: 'POST', data: { content } }),
  )
}

export function listDiaryComments(id: number) {
  return invoke(
    async () => (await mockService.diary.comments(id)).data as unknown[],
    () => request<unknown[]>({ url: `/diary/${id}/comments`, method: 'GET' }),
  )
}

export function autoGenerateDiary() {
  return invoke(
    async () => (await mockService.diary.autoGenerate()).data as Record<string, unknown>,
    () => request<Record<string, unknown>>({ url: '/diary/auto-generate', method: 'POST' }),
  )
}

