package org.dsgroup.journeycraft.diary.vo.rspvo;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * 日记详情响应 VO
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "日记详情响应")
public class DiaryDetailRspVO {

    @Schema(description = "日记 ID", example = "65f8a1b2c3d4e5f6a7b8c9d0")
    private String id;

    @Schema(description = "作者 ID", example = "1001")
    private Long userId;

    @Schema(description = "作者昵称", example = "旅行达人")
    private String userNickname;

    @Schema(description = "作者头像", example = "http://localhost:9000/journeycraft/avatar/user_1001.jpg")
    private String userAvatar;

    @Schema(description = "标题", example = "黄山三日游 - 云海奇观")
    private String title;

    @Schema(description = "内容 (Markdown)", example = "# 黄山之旅\n\n第一天...")
    private String content;

    @Schema(description = "景区 ID 列表", example = "[1001, 1002]")
    private List<Long> scenicAreaId;

    @Schema(description = "行程 ID", example = "2001")
    private Long tripId;

    @Schema(description = "封面图", example = "http://localhost:9000/journeycraft/diary/cover_001.jpg")
    private String coverImage;

    @Schema(description = "图片列表", example = "[\"http://...\"]")
    private List<String> images;

    @Schema(description = "视频列表", example = "[\"http://...\"]")
    private List<String> videos;

    @Schema(description = "游览路径", example = "[]")
    private List<PathNodeVO> path;

    @Schema(description = "标签", example = "[\"自然风光\", \"登山\"]")
    private List<String> tags;

    @Schema(description = "评分 0-5", example = "4.8")
    private Double rating;

    @Schema(description = "心情", example = "兴奋")
    private String mood;

    @Schema(description = "天气", example = "晴朗")
    private String weather;

    @Schema(description = "同行人", example = "[\"张三\", \"李四\"]")
    private List<String> companions;

    @Schema(description = "是否 AI 生成", example = "false")
    private Boolean isAutoGenerated;

    @Schema(description = "AI 摘要", example = "...")
    private String aiSummary;

    @Schema(description = "点赞数", example = "128")
    private Long likeCount;

    @Schema(description = "浏览数", example = "1523")
    private Long viewCount;

    @Schema(description = "评论数", example = "32")
    private Long commentCount;

    @Schema(description = "是否已点赞", example = "false")
    private Boolean isLiked;

    @Schema(description = "状态：0-私密 1-公开", example = "1")
    private Integer status;

    @Schema(description = "创建时间", example = "2024-03-15T10:30:00Z")
    private java.time.LocalDateTime createdAt;

    @Schema(description = "更新时间", example = "2024-03-15T14:20:00Z")
    private java.time.LocalDateTime updatedAt;

    /**
     * 游览路径节点 VO
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "游览路径节点")
    public static class PathNodeVO {

        @Schema(description = "节点名称", example = "太和殿")
        private String nodeName;

        @Schema(description = "节点 ID", example = "20")
        private Long nodeId;

        @Schema(description = "时间戳", example = "2024-04-01T09:30:00")
        private java.time.LocalDateTime timestamp;

        @Schema(description = "纬度", example = "39.915")
        private Double lat;

        @Schema(description = "经度", example = "116.397")
        private Double lng;

        @Schema(description = "照片数量", example = "20")
        private Integer photoCount;

        @Schema(description = "节点图片列表")
        private List<String> images;

        @Schema(description = "节点视频列表")
        private List<String> videos;
    }
}
